- hosts: all

  vars_files:
    - secret.yaml

  vars:
    myservice_password: "{{ vault_myservice_password }}"
  
  tasks:
    - name: Copy config file
      template:
        src: config.json.j2
        dest: ~/config.json
